import type { ReactNode } from "react";
import type { Metadata } from "next";

// Material UI
import { CssBaseline, Stack, ThemeProvider } from "@mui/material";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import { theme } from "@/theme";

// Providers
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { TSQueryProvider } from "@/providers/tsquery.provider";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

export const metadata: Metadata = {
  title: "User Management",
  description: "Generated by create next app",
  icons: "user-management-icon.png"
};

export default function RootLayout({
  children
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.png" type="image/png" />
        <link rel="preload" href="/images/background_login.jpg" as="image" />
      </head>
      <body>
        <InitColorSchemeScript attribute="class" />
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
            <CssBaseline />
            <Stack
              height="100vh"
              width="100vw"
              overflow="hidden"
              sx={{ background: "background.main" }}
            >
              <TSQueryProvider>{children}</TSQueryProvider>
            </Stack>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
