CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Define types
CREATE TYPE user_role AS ENUM ('admin', 'user');
CREATE TYPE user_status AS ENUM ('active', 'inactive');

-- Create users table
CREATE TABLE users (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),  -- UUID v4 autogenerated
    "firstName" VARCHAR(255) NOT NULL,
    "lastName" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,  -- email único
    "password" VARCHAR(100) NOT NULL,
    "phoneNumber" VARCHAR(20),
    "role" user_role NOT NULL,
    "status" user_status NOT NULL,
    "address" JSONB,
    "profilePictureURL" TEXT
);

INSERT INTO users ("firstName", "lastName", "email", "password", "phoneNumber", "role", "status", "address", "profilePictureURL")
VALUES
  ('Martín', 'Pérez', 'admin@example.com', crypt('password', gen_salt('bf')), '+1122334455', 'user', 'active', '{"street": "Third St", "number": "789", "city": "Chicago", "postalCode": 60601}', 'https://media.licdn.com/dms/image/v2/D5603AQHFWO5kry8ZBg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1673652312252?e=2147483647&v=beta&t=xcmr85p85iC4XEEaL6CSJ8jV8PAUzio270zShHCYl7U'),
  ('John', 'Doe', 'john.doe@example.com', 'abc123', '+1234567890', 'user', 'active', '{"street": "Main St", "number": "123", "city": "New York", "postalCode": 10001}', 'https://example.com/profiles/john.jpg'),
  ('Jane', 'Smith', 'jane.smith@example.com', 'abc123', '+0987654321', 'admin', 'inactive', '{"street": "Second St", "number": "456", "city": "Los Angeles", "postalCode": 90001}', 'https://example.com/profiles/jane.jpg'),
  ('Bob', 'Brown', 'bob.brown@example.com', 'abc123', '+2233445566', 'user', 'active', '{"street": "Fourth St", "number": "101", "city": "Houston", "postalCode": 77001}', 'https://example.com/profiles/bob.jpg'),
  ('Charlie', 'Davis', 'charlie.davis@example.com', 'abc123', '+3344556677', 'admin', 'inactive', '{"street": "Fifth St", "number": "202", "city": "Phoenix", "postalCode": 85001}', 'https://example.com/profiles/charlie.jpg'),
  ('Diana', 'Evans', 'diana.evans@example.com', 'abc123', '+4455667788', 'user', 'active', '{"street": "Sixth St", "number": "303", "city": "Philadelphia", "postalCode": 19019}', 'https://example.com/profiles/diana.jpg'),
  ('Eva', 'Garcia', 'eva.garcia@example.com', 'abc123', '+5566778899', 'user', 'active', '{"street": "Seventh St", "number": "404", "city": "San Antonio", "postalCode": 78201}', 'https://example.com/profiles/eva.jpg'),
  ('Frank', 'Harris', 'frank.harris@example.com', 'abc123', '+6677889900', 'admin', 'inactive', '{"street": "Eighth St", "number": "505", "city": "San Diego", "postalCode": 92101}', 'https://example.com/profiles/frank.jpg'),
  ('Grace', 'Lee', 'grace.lee@example.com', 'abc123', '+7788990011', 'user', 'active', '{"street": "Ninth St", "number": "606", "city": "Dallas", "postalCode": 75201}', 'https://example.com/profiles/grace.jpg'),
  ('Henry', 'Martinez', 'henry.martinez@example.com', 'abc123', '+8899001122', 'user', 'active', '{"street": "Tenth St", "number": "707", "city": "San Jose", "postalCode": 95101}', 'https://example.com/profiles/henry.jpg'),
  ('Ivy', 'Nelson', 'ivy.nelson@example.com', 'abc123', '+9900112233', 'admin', 'inactive', '{"street": "Eleventh St", "number": "808", "city": "Austin", "postalCode": 73301}', 'https://example.com/profiles/ivy.jpg'),
  ('Jack', 'Perez', 'jack.perez@example.com', 'abc123', '+0011223344', 'user', 'active', '{"street": "Twelfth St", "number": "909", "city": "Jacksonville", "postalCode": 32099}', 'https://example.com/profiles/jack.jpg'),
  ('Karen', 'Robinson', 'karen.robinson@example.com', 'abc123', '+1122334455', 'user', 'active', '{"street": "Thirteenth St", "number": "1010", "city": "San Francisco", "postalCode": 94101}', 'https://example.com/profiles/karen.jpg'),
  ('Leo', 'Scott', 'leo.scott@example.com', 'abc123', '+2233445566', 'admin', 'inactive', '{"street": "Fourteenth St", "number": "1111", "city": "Indianapolis", "postalCode": 46201}', 'https://example.com/profiles/leo.jpg'),
  ('Mia', 'Taylor', 'mia.taylor@example.com', 'abc123', '+3344556677', 'user', 'active', '{"street": "Fifteenth St", "number": "1212", "city": "Columbus", "postalCode": 43085}', 'https://example.com/profiles/mia.jpg'),
  ('Noah', 'White', 'noah.white@example.com', 'abc123', '+4455667788', 'user', 'active', '{"street": "Sixteenth St", "number": "1313", "city": "Charlotte", "postalCode": 28201}', 'https://example.com/profiles/noah.jpg'),
  ('Olivia', 'Young', 'olivia.young@example.com', 'abc123', '+5566778899', 'admin', 'inactive', '{"street": "Seventeenth St", "number": "1414", "city": "Seattle", "postalCode": 98101}', 'https://example.com/profiles/olivia.jpg'),
  ('Peter', 'Allen', 'peter.allen@example.com', 'abc123', '+6677889900', 'user', 'active', '{"street": "Eighteenth St", "number": "1515", "city": "Denver", "postalCode": 80201}', 'https://example.com/profiles/peter.jpg'),
  ('Quinn', 'Baker', 'quinn.baker@example.com', 'abc123', '+7788990011', 'user', 'active', '{"street": "Nineteenth St", "number": "1616", "city": "Washington", "postalCode": 20001}', 'https://example.com/profiles/quinn.jpg'),
  ('Rachel', 'Carter', 'rachel.carter@example.com', 'abc123', '+8899001122', 'admin', 'inactive', '{"street": "Twentieth St", "number": "1717", "city": "Boston", "postalCode": 62101}', 'https://example.com/profiles/rachel.jpg'),
  ('Samuel', 'Clark', 'samuel.clark@example.com', 'abc123', '+1234567890', 'user', 'active', '{"street": "Oak St", "number": "1818", "city": "Atlanta", "postalCode": 30301}', 'https://example.com/profiles/samuel.jpg'),
  ('Tina', 'Flores', 'tina.flores@example.com', 'abc123', '+2345678901', 'admin', 'inactive', '{"street": "Pine St", "number": "1919", "city": "Detroit", "postalCode": 48201}', 'https://example.com/profiles/tina.jpg'),
  ('Victor', 'Gomez', 'victor.gomez@example.com', 'abc123', '+3456789012', 'user', 'active', '{"street": "Maple St", "number": "2020", "city": "Portland", "postalCode": 97201}', 'https://example.com/profiles/victor.jpg'),
  ('Wendy', 'Hernandez', 'wendy.hernandez@example.com', 'abc123', '+4567890123', 'user', 'active', '{"street": "Cedar St", "number": "2121", "city": "Las Vegas", "postalCode": 89101}', 'https://example.com/profiles/wendy.jpg'),
  ('Xander', 'Irwin', 'xander.irwin@example.com', 'abc123', '+5678901234', 'admin', 'inactive', '{"street": "Elm St", "number": "2222", "city": "Baltimore", "postalCode": 21201}', 'https://example.com/profiles/xander.jpg'),
  ('Yara', 'Jimenez', 'yara.jimenez@example.com', 'abc123', '+6789012345', 'user', 'active', '{"street": "Birch St", "number": "2323", "city": "Memphis", "postalCode": 37501}', 'https://example.com/profiles/yara.jpg'),
  ('Zack', 'Klein', 'zack.klein@example.com', 'abc123', '+7890123456', 'user', 'active', '{"street": "Willow St", "number": "2424", "city": "Milwaukee", "postalCode": 53201}', 'https://example.com/profiles/zack.jpg'),
  ('Ava', 'Lopez', 'ava.lopez@example.com', 'abc123', '+8901234567', 'admin', 'inactive', '{"street": "Cypress St", "number": "2525", "city": "Albuquerque", "postalCode": 87101}', 'https://example.com/profiles/ava.jpg'),
  ('Ben', 'Mason', 'ben.mason@example.com', 'abc123', '+9012345678', 'user', 'active', '{"street": "Magnolia St", "number": "2626", "city": "Tucson", "postalCode": 85701}', 'https://example.com/profiles/ben.jpg'),
  ('Cara', 'Norton', 'cara.norton@example.com', 'abc123', '+0123456789', 'user', 'active', '{"street": "Juniper St", "number": "2727", "city": "Fresno", "postalCode": 93650}', 'https://example.com/profiles/cara.jpg'),
  ('Derek', 'Owens', 'derek.owens@example.com', 'abc123', '+1234509876', 'admin', 'inactive', '{"street": "Sycamore St", "number": "2828", "city": "Sacramento", "postalCode": 94203}', 'https://example.com/profiles/derek.jpg'),
  ('Ella', 'Patel', 'ella.patel@example.com', 'abc123', '+2345610987', 'user', 'active', '{"street": "Poplar St", "number": "2929", "city": "Kansas City", "postalCode": 64101}', 'https://example.com/profiles/ella.jpg'),
  ('Felix', 'Quinn', 'felix.quinn@example.com', 'abc123', '+3456721098', 'user', 'active', '{"street": "Redwood St", "number": "3030", "city": "Miami", "postalCode": 33101}', 'https://example.com/profiles/felix.jpg'),
  ('Gina', 'Rivera', 'gina.rivera@example.com', 'abc123', '+4567832109', 'admin', 'inactive', '{"street": "Spruce St", "number": "3131", "city": "Raleigh", "postalCode": 27601}', 'https://example.com/profiles/gina.jpg'),
  ('Hank', 'Stewart', 'hank.stewart@example.com', 'abc123', '+5678943210', 'user', 'active', '{"street": "Fir St", "number": "3232", "city": "Omaha", "postalCode": 68101}', 'https://example.com/profiles/hank.jpg'),
  ('Iris', 'Torres', 'iris.torres@example.com', 'abc123', '+6789054321', 'user', 'active', '{"street": "Hemlock St", "number": "3333", "city": "Minneapolis", "postalCode": 55401}', 'https://example.com/profiles/iris.jpg'),
  ('Jake', 'Underwood', 'jake.underwood@example.com', 'abc123', '+7890165432', 'admin', 'inactive', '{"street": "Dogwood St", "number": "3434", "city": "Tampa", "postalCode": 33601}', 'https://example.com/profiles/jake.jpg'),
  ('Kara', 'Vega', 'kara.vega@example.com', 'abc123', '+8901276543', 'user', 'active', '{"street": "Cherry St", "number": "3535", "city": "Pittsburgh", "postalCode": 15201}', 'https://example.com/profiles/kara.jpg'),
  ('Liam', 'Watson', 'liam.watson@example.com', 'abc123', '+9012387654', 'user', 'active', '{"street": "Ash St", "number": "3636", "city": "Cincinnati", "postalCode": 45201}', 'https://example.com/profiles/liam.jpg'),
  ('Mona', 'Xu', 'mona.xu@example.com', 'abc123', '+0123498765', 'admin', 'inactive', '{"street": "Beech St", "number": "3737", "city": "Anaheim", "postalCode": 92801}', 'https://example.com/profiles/mona.jpg'),
  ('Nate', 'Yates', 'nate.yates@example.com', 'abc123', '+1234509876', 'user', 'active', '{"street": "Chestnut St", "number": "3838", "city": "Honolulu", "postalCode": 96801}', 'https://example.com/profiles/nate.jpg'),
  ('Olga', 'Zimmerman', 'olga.zimmerman@example.com', 'abc123', '+2345610987', 'user', 'active', '{"street": "Hickory St", "number": "3939", "city": "Orlando", "postalCode": 32801}', 'https://example.com/profiles/olga.jpg'),
  ('Paul', 'Adams', 'paul.adams@example.com', 'abc123', '+3456721098', 'admin', 'inactive', '{"street": "Locust St", "number": "4040", "city": "St. Louis", "postalCode": 63101}', 'https://example.com/profiles/paul.jpg'),
  ('Quincy', 'Bennett', 'quincy.bennett@example.com', 'abc123', '+4567832109', 'user', 'active', '{"street": "Mulberry St", "number": "4141", "city": "New Orleans", "postalCode": 70112}', 'https://example.com/profiles/quincy.jpg'),
  ('Rita', 'Cruz', 'rita.cruz@example.com', 'abc123', '+5678943210', 'user', 'active', '{"street": "Palm St", "number": "4242", "city": "Buffalo", "postalCode": 14201}', 'https://example.com/profiles/rita.jpg'),
  ('Steve', 'Dunn', 'steve.dunn@example.com', 'abc123', '+6789054321', 'admin', 'inactive', '{"street": "Pear St", "number": "4343", "city": "Riverside", "postalCode": 92501}', 'https://example.com/profiles/steve.jpg'),
  ('Tara', 'Elliott', 'tara.elliott@example.com', 'abc123', '+7890165432', 'user', 'active', '{"street": "Plum St", "number": "4444", "city": "Santa Ana", "postalCode": 92701}', 'https://example.com/profiles/tara.jpg'),
  ('Umar', 'Foster', 'umar.foster@example.com', 'abc123', '+8901276543', 'user', 'active', '{"street": "Walnut St", "number": "4545", "city": "Corpus Christi", "postalCode": 78401}', 'https://example.com/profiles/umar.jpg'),
  ('Vera', 'Graham', 'vera.graham@example.com', 'abc123', '+9012387654', 'admin', 'inactive', '{"street": "Willow St", "number": "4646", "city": "Newark", "postalCode": 17101}', 'https://example.com/profiles/vera.jpg'),
  ('Wade', 'Hughes', 'wade.hughes@example.com', 'abc123', '+0123498765', 'user', 'active', '{"street": "Yew St", "number": "4747", "city": "Lexington", "postalCode": 40502}', 'https://example.com/profiles/wade.jpg');


-- Add indexes
CREATE INDEX idx_users_firstName_trgm ON users USING gin ("firstName" gin_trgm_ops);
CREATE INDEX idx_users_lastName_trgm ON users USING gin ("lastName" gin_trgm_ops);
CREATE INDEX idx_users_email_trgm ON users USING gin ("email" gin_trgm_ops);